In [ ]:
import torch
from torch import nn
import torchvision
import PIL
from torchinfo import summary

: 

In [14]:
import pandas as pd
import numpy as np
import plotly.express as px

ModuleNotFoundError: No module named 'pandas'

In [3]:
gpu=torch_directml.device(0)
gpu

device(type='privateuseone', index=0)

In [4]:
transform=torchvision.transforms.ToTensor()

In [5]:
train_data=torchvision.datasets.MNIST(root="mnist",transform=transform)

In [6]:
images,labels=[],[]

In [7]:
for i in train_data:
    image,label=i
    images.append(image)
    labels.append(label)
images=torch.Tensor(np.array(images))#.to(gpu)
labels=torch.Tensor(np.array(labels))#.to(gpu)
image

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [8]:
images

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [9]:
labels

tensor([5., 0., 4.,  ..., 5., 6., 8.])

In [10]:
test_data=torchvision.datasets.MNIST(train=False,root="mnist",transform=transform)

In [21]:
test_labels,test_images=[],[]

In [22]:
for i in test_data:
    image,label=i
    test_images.append(image)
    test_labels.append(label)
test_images=torch.Tensor(np.array(test_images)).to(gpu)
test_labels=torch.LongTensor(np.array(test_labels)).to(gpu)

In [23]:
test_images

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [38]:
class MultiClassifier(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.layer1=nn.Sequential(
            nn.Conv2d(in_channels=1,out_channels=10,kernel_size=1,padding=1),
            nn.ReLU(),
            nn.Flatten(),
            nn.Linear(9000,100),
            nn.ReLU(),
            nn.Linear(100,10),
            nn.Linear(10,10),
            nn.LogSoftmax(),
        )
    def forward(self,x):
        return (self.layer1(x)).argmax()

In [39]:
model1=MultiClassifier()#.to(gpu)
summary(model1)

Layer (type:depth-idx)                   Param #
MultiClassifier                          --
├─Sequential: 1-1                        --
│    └─Conv2d: 2-1                       20
│    └─ReLU: 2-2                         --
│    └─Flatten: 2-3                      --
│    └─Linear: 2-4                       900,100
│    └─ReLU: 2-5                         --
│    └─Linear: 2-6                       1,010
│    └─Linear: 2-7                       110
│    └─LogSoftmax: 2-8                   --
Total params: 901,240
Trainable params: 901,240
Non-trainable params: 0

In [40]:
loss_func=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(lr=0.01,params=model1.parameters())

In [41]:
epochs=1
for epoch in range(epochs):
    y_res=model1.forward(images)
    print(y_res)
    loss=loss_func(y_res,labels)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(loss)

c:\Users\praty\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py:1553: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor(95836)


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [125]:
images.shape

torch.Size([60000, 1, 28, 28])

In [83]:
images[0]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,