In [1]:
import torch
from torch import nn
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Heart Prediction Quantum Dataset.csv")

In [3]:
df

Age  Gender  BloodPressure  Cholesterol  HeartRate  \
0     68       1            105          191        107   
1     58       0             97          249         89   
2     44       0             93          190         82   
3     72       1             93          183        101   
4     37       0            145          166        103   
..   ...     ...            ...          ...        ...   
495   34       0            126          292        116   
496   41       0            164          248        114   
497   45       1            159          175         75   
498   55       0            107          157        101   
499   55       0            174          249         89   

     QuantumPatternFeature  HeartDisease  
0                 8.362241             1  
1                 9.249002             0  
2                 7.942542             1  
3                 6.495155             1  
4                 7.653900             1  
..                     ...           ...  
495               9.303403             0  
496               9.067889             0  
497               8.718708             0  
498               7.337650             1  
499              10.492950             0  

[500 rows x 7 columns]

In [4]:
x=df.drop(axis=1,columns=["HeartDisease"])
y=df["HeartDisease"]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2)

In [7]:
x_test

Age  Gender  BloodPressure  Cholesterol  HeartRate  QuantumPatternFeature
442   68       0            144          161         92               6.510760
159   68       0             99          212         76               8.056395
119   37       0            113          153         90               7.420972
351   48       1            140          280        114               9.935508
357   57       0            159          297         68              10.428418
..   ...     ...            ...          ...        ...                    ...
441   34       0            103          236         96               8.214240
228   61       0            142          194        119               9.415611
221   61       1            112          295         60               8.229842
394   55       0            107          241         93               8.197138
272   71       0            134          247         65               7.722952

[100 rows x 6 columns]

In [8]:
x_train=torch.Tensor(np.array(x_train))
y_train=torch.unsqueeze(torch.Tensor(np.array(y_train)),dim=1)
x_test=torch.Tensor(np.array(x_test))
y_test=torch.unsqueeze(torch.Tensor(np.array(y_test)),dim=1)

In [9]:
y_test

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
      

In [49]:
class DiseasePredict(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.layer1=nn.Sequential(
            nn.Linear(in_features=6,out_features=16),
            nn.Linear(in_features=16,out_features=32),
            nn.Dropout(0.30),
            nn.Linear(in_features=32,out_features=16),
            nn.Dropout(0.30),
            nn.ReLU(),
            nn.Linear(in_features=16,out_features=1),
            nn.Sigmoid()
            
        )
    def forward(self,x):
        return (self.layer1(x))


In [50]:
model=DiseasePredict()

In [102]:
loss_fn=nn.BCELoss()
optimizer=torch.optim.Adam(lr=0.001,params=model.parameters())

In [109]:
epochs=10
for epoch in range(epochs):
    model.train()
    y_preds=model.forward(x_train)
    print(y_preds)
    loss=loss_fn(y_preds,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(loss)

tensor([[0.5312],
        [0.5610],
        [0.6764],
        [0.9991],
        [0.9995],
        [0.7316],
        [0.7925],
        [0.4598],
        [0.9928],
        [0.6045],
        [0.4568],
        [0.5462],
        [0.5739],
        [0.7621],
        [0.2659],
        [0.4378],
        [0.3498],
        [0.9714],
        [0.6622],
        [0.5312],
        [0.5365],
        [0.8343],
        [0.9094],
        [0.9993],
        [0.5289],
        [0.5005],
        [0.3152],
        [0.4877],
        [0.5312],
        [0.8604],
        [0.8883],
        [0.3483],
        [0.9978],
        [0.5495],
        [0.8277],
        [0.4129],
        [0.5312],
        [0.3489],
        [0.7200],
        [0.5927],
        [0.3481],
        [0.4454],
        [0.8558],
        [0.5312],
        [1.0000],
        [0.9914],
        [0.7299],
        [0.6316],
        [0.5550],
        [0.5312],
        [0.3626],
        [0.3614],
        [0.5638],
        [0.8667],
        [0.5893],
        [0

In [110]:
with torch.inference_mode():
    y_res=model.forward(x_test)
    for i in range(len(y_res)):
        y_res[i]=round(float(y_res[i]))
    print(y_res)


tensor([[1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
      

In [111]:
y_test

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],

In [112]:
y_test=np.array(y_test)
y_res=np.array(y_res)

In [113]:
res=np.equal(y_res,y_test)
res

array([[ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [

In [114]:
c=0
for i in res:
    if i:
        c+=1
c

63