In [1]:
import torch
from torch import nn
import plotly.express as px
import sklearn
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Heart Prediction Quantum Dataset.csv")

In [3]:
in_features=len(df.columns)-1

In [4]:
df["QuantumPatternFeature"]

0       8.362241
1       9.249002
2       7.942542
3       6.495155
4       7.653900
         ...    
495     9.303403
496     9.067889
497     8.718708
498     7.337650
499    10.492950
Name: QuantumPatternFeature, Length: 500, dtype: float64

In [5]:
df["Gender"]

0      1
1      0
2      0
3      1
4      0
      ..
495    0
496    0
497    1
498    0
499    0
Name: Gender, Length: 500, dtype: int64

In [6]:
class Classifier(nn.Module):
    def __init__(self, **kwargs):
        super().__init__()
        self.layer1=nn.Sequential(
            nn.Linear(in_features,32),
            nn.ReLU(),
            nn.Linear(32,64),
            nn.Dropout(0.25),
            nn.Linear(64,16),
            nn.Sigmoid(),
            nn.Linear(16,1)
        )
        
    
    def forward(self,x):
        return self.layer1(x)

In [7]:
df

Age  Gender  BloodPressure  Cholesterol  HeartRate  \
0     68       1            105          191        107   
1     58       0             97          249         89   
2     44       0             93          190         82   
3     72       1             93          183        101   
4     37       0            145          166        103   
..   ...     ...            ...          ...        ...   
495   34       0            126          292        116   
496   41       0            164          248        114   
497   45       1            159          175         75   
498   55       0            107          157        101   
499   55       0            174          249         89   

     QuantumPatternFeature  HeartDisease  
0                 8.362241             1  
1                 9.249002             0  
2                 7.942542             1  
3                 6.495155             1  
4                 7.653900             1  
..                     ...           ...  
495               9.303403             0  
496               9.067889             0  
497               8.718708             0  
498               7.337650             1  
499              10.492950             0  

[500 rows x 7 columns]

In [8]:
x=torch.Tensor(df.drop(["HeartDisease"],axis=1).to_numpy())
y=torch.Tensor(df["HeartDisease"].to_numpy())

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:
x_train

tensor([[ 51.0000,   1.0000, 148.0000, 199.0000,  76.0000,   8.8898],
        [ 51.0000,   1.0000, 153.0000, 155.0000,  70.0000,   8.3169],
        [ 41.0000,   0.0000, 142.0000, 150.0000,  66.0000,   9.1512],
        ...,
        [ 33.0000,   1.0000,  92.0000, 186.0000,  69.0000,   9.0491],
        [ 57.0000,   0.0000, 121.0000, 221.0000,  84.0000,   7.9975],
        [ 32.0000,   0.0000, 140.0000, 182.0000,  84.0000,   7.7132]])

In [12]:
x_test

tensor([[ 50.0000,   1.0000, 114.0000, 271.0000,  73.0000,   8.6316],
        [ 62.0000,   0.0000, 136.0000, 151.0000,  80.0000,   6.8984],
        [ 65.0000,   1.0000, 179.0000, 279.0000, 108.0000,   9.1807],
        [ 71.0000,   1.0000, 103.0000, 222.0000,  93.0000,   7.1834],
        [ 70.0000,   1.0000, 102.0000, 287.0000,  85.0000,   8.5965],
        [ 57.0000,   0.0000,  97.0000, 188.0000, 103.0000,   7.9620],
        [ 42.0000,   0.0000, 102.0000, 201.0000,  71.0000,   7.1339],
        [ 40.0000,   0.0000, 118.0000, 161.0000,  74.0000,   7.7657],
        [ 65.0000,   0.0000, 122.0000, 238.0000,  85.0000,   7.3811],
        [ 32.0000,   0.0000, 170.0000, 254.0000,  93.0000,   8.5092],
        [ 47.0000,   0.0000, 160.0000, 244.0000,  95.0000,   9.7341],
        [ 45.0000,   1.0000, 170.0000, 257.0000, 103.0000,   9.6069],
        [ 59.0000,   0.0000, 122.0000, 210.0000,  89.0000,   9.3736],
        [ 38.0000,   0.0000, 136.0000, 258.0000,  75.0000,   9.0400],
        [ 58.0000,  

In [29]:
model=Classifier(in_features=in_features)

In [36]:
loss_func=nn.BCELoss()
optimizer=torch.optim.Adam(lr=0.01,params=model.parameters())

In [31]:
x_train.shape

torch.Size([400, 6])

In [16]:
y_train.shape
y_train=torch.unsqueeze(y_train,dim=1)
y_test=torch.unsqueeze(y_test,dim=1)
y_train

tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
      

In [37]:
epochs=10
for epoch in range(epochs):
    model.train()
    y_preds=model.forward(x_train)
    print(y_preds)
    loss=loss_func(y_preds,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(loss)

tensor([[ 0.3588],
        [ 0.1284],
        [-0.2571],
        [-0.0297],
        [ 0.3614],
        [-0.0122],
        [ 0.3450],
        [ 0.3817],
        [-0.0261],
        [ 0.0106],
        [ 0.1989],
        [-0.0504],
        [-0.0732],
        [-0.0939],
        [-0.0141],
        [ 0.1230],
        [-0.1841],
        [-0.1017],
        [-0.0359],
        [ 0.1773],
        [ 0.2005],
        [ 0.1083],
        [-0.1191],
        [ 0.0684],
        [ 0.0467],
        [ 0.1102],
        [ 0.3925],
        [ 0.3848],
        [ 0.0114],
        [-0.1134],
        [-0.0163],
        [ 0.0649],
        [ 0.1614],
        [ 0.4440],
        [ 0.4462],
        [ 0.4894],
        [ 0.1573],
        [-0.1146],
        [-0.0787],
        [ 0.1928],
        [-0.0921],
        [ 0.1705],
        [ 0.1272],
        [ 0.1829],
        [ 0.0677],
        [ 0.1936],
        [ 0.3154],
        [-0.0016],
        [-0.0687],
        [-0.1104],
        [ 0.1777],
        [ 0.0260],
        [-0.

RuntimeError: all elements of input should be between 0 and 1

In [ ]:
y_res=model.forward(x_test)
y_res=list(y_res)
y_res

In [ ]:
x=0
for i in range(len(y_res)):
    if int(int(y_test[i])==round(float(y_res[i]))):
        x+=1
x