In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import tensorflow as tf

In [6]:
x=tf.Variable(100.11)

In [7]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=100.11>

In [8]:
y=tf.Variable([[4.0]])
y

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[4.]], dtype=float32)>

In [9]:
z=tf.zeros(10)
z

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [10]:
i=tf.eye(3)
i

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [11]:
u=tf.random.uniform(shape=[10,1],minval=-1,maxval=1)
u

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.23200727],
       [-0.5083606 ],
       [-0.43458295],
       [-0.6827915 ],
       [-0.48472786],
       [ 0.5075307 ],
       [ 0.99245524],
       [-0.9670007 ],
       [ 0.7649741 ],
       [-0.67801857]], dtype=float32)>

In [16]:
from tensorflow import keras

In [15]:
from tensorflow.keras.datasets import mnist

ModuleNotFoundError: No module named 'tensorflow.keras'

In [22]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [23]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [24]:
x_train.shape

(60000, 28, 28)

In [27]:
x_train=x_train.reshape(-1,28*28).astype('float32')

In [28]:
x_test=x_test.reshape(-1,28*28).astype('float32')

In [29]:
model=keras.Sequential([
    layers.Dense(512,activation="relu"),
    layers.Dense(256,activation="relu"),
    layers.Dense(10),
])

In [32]:
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])

In [33]:
model.fit(x_train,y_train,epochs=10,verbose=2)

Epoch 1/10
1875/1875 - 7s - 4ms/step - accuracy: 0.9038 - loss: 1.4279
Epoch 2/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9457 - loss: 0.2028
Epoch 3/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9544 - loss: 0.1721
Epoch 4/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9586 - loss: 0.1503
Epoch 5/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9627 - loss: 0.1374
Epoch 6/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9682 - loss: 0.1213
Epoch 7/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9706 - loss: 0.1152
Epoch 8/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9750 - loss: 0.0980
Epoch 9/10
1875/1875 - 6s - 3ms/step - accuracy: 0.9776 - loss: 0.0899
Epoch 10/10
1875/1875 - 5s - 3ms/step - accuracy: 0.9785 - loss: 0.0825


In [34]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9689 - loss: 0.1627


[0.162698432803154, 0.9689000248908997]