In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2=np.array([[7,4,5,6,2,3,4],
              [8,6,5,1,2,3,7]])

In [6]:
arr2

array([[7, 4, 5, 6, 2, 3, 4],
       [8, 6, 5, 1, 2, 3, 7]])

In [7]:
arr2.shape

(2, 7)

In [8]:
arr1.shape

(10,)

In [9]:
arr2.ndim

2

In [10]:
arr2.dtype

dtype('int64')

In [11]:
arr2.size

14

In [12]:
ones=np.ones((2,3),dtype=int)

In [13]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
zeroes=np.zeros((2,3),dtype=int)

In [15]:
zeroes

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
range_array=np.arange(0,11,2)

In [17]:
range_array

array([ 0,  2,  4,  6,  8, 10])

In [18]:
range_array.dtype

dtype('int64')

In [19]:
random_array=np.random.randint(0,10,size=(3,3))

In [20]:
random_array

array([[5, 4, 5],
       [4, 1, 7],
       [8, 0, 7]], dtype=int32)

In [21]:
np.random.seed(seed=0)
array_3=np.random.randint(1,11,size=(5,5))
array_3

array([[ 6,  1,  4,  4,  8],
       [10,  4,  6,  3,  5],
       [ 8,  7,  9,  9,  2],
       [ 7,  8,  8,  9,  2],
       [ 6, 10,  9, 10,  5]], dtype=int32)

In [22]:
test_array=np.random.randint(1,11,size=(3,4,5,6))
test_array

array([[[[ 4,  1,  4,  6,  1,  3],
         [ 4,  9,  2,  4,  4,  4],
         [ 8,  1,  2, 10, 10,  1],
         [ 5,  8,  4,  3,  8,  3],
         [ 1,  1,  5,  6,  6,  7]],

        [[ 9,  5,  2,  5, 10,  9],
         [ 2,  2,  8, 10, 10,  4],
         [ 7,  8,  3,  1,  4,  6],
         [10,  5,  5,  7,  5,  5],
         [ 4,  5,  5,  9,  5,  4]],

        [[ 8,  6,  6,  1,  2,  6],
         [10,  4,  1,  6,  1,  2],
         [ 3,  5,  3,  1,  4,  3],
         [ 1,  8,  6, 10,  1,  3],
         [ 8,  3, 10,  3,  4,  4]],

        [[ 3,  4,  5,  2,  3, 10],
         [ 2,  5,  7,  9,  3,  4],
         [ 1,  1,  7,  1,  7,  4],
         [ 4,  9,  9,  9,  3,  4],
         [ 3,  1,  9,  9,  4,  9]]],


       [[[ 3,  9,  5,  4,  1,  5],
         [ 4,  7, 10,  9,  1,  9],
         [ 6, 10,  1, 10,  7,  6],
         [ 4,  2,  9,  1,  5, 10],
         [ 7,  6,  8,  9,  9, 10]],

        [[ 3,  9,  7,  7, 10,  2],
         [ 7,  9,  9,  4,  3,  4],
         [ 7,  4,  7,  6,  8,  1],
        

In [23]:
test_array[:2,:2,:2,:2]

array([[[[4, 1],
         [4, 9]],

        [[9, 5],
         [2, 2]]],


       [[[3, 9],
         [4, 7]],

        [[3, 9],
         [7, 9]]]], dtype=int32)

In [24]:
test2=np.random.randint(0,10,size=(3,3))
test2

array([[0, 3, 8],
       [4, 1, 4],
       [5, 0, 3]], dtype=int32)

In [25]:
test2[:2]

array([[0, 3, 8],
       [4, 1, 4]], dtype=int32)

In [26]:
test2

array([[0, 3, 8],
       [4, 1, 4],
       [5, 0, 3]], dtype=int32)

In [27]:
test2[:2,:2]

array([[0, 3],
       [4, 1]], dtype=int32)

In [28]:
test_array

array([[[[ 4,  1,  4,  6,  1,  3],
         [ 4,  9,  2,  4,  4,  4],
         [ 8,  1,  2, 10, 10,  1],
         [ 5,  8,  4,  3,  8,  3],
         [ 1,  1,  5,  6,  6,  7]],

        [[ 9,  5,  2,  5, 10,  9],
         [ 2,  2,  8, 10, 10,  4],
         [ 7,  8,  3,  1,  4,  6],
         [10,  5,  5,  7,  5,  5],
         [ 4,  5,  5,  9,  5,  4]],

        [[ 8,  6,  6,  1,  2,  6],
         [10,  4,  1,  6,  1,  2],
         [ 3,  5,  3,  1,  4,  3],
         [ 1,  8,  6, 10,  1,  3],
         [ 8,  3, 10,  3,  4,  4]],

        [[ 3,  4,  5,  2,  3, 10],
         [ 2,  5,  7,  9,  3,  4],
         [ 1,  1,  7,  1,  7,  4],
         [ 4,  9,  9,  9,  3,  4],
         [ 3,  1,  9,  9,  4,  9]]],


       [[[ 3,  9,  5,  4,  1,  5],
         [ 4,  7, 10,  9,  1,  9],
         [ 6, 10,  1, 10,  7,  6],
         [ 4,  2,  9,  1,  5, 10],
         [ 7,  6,  8,  9,  9, 10]],

        [[ 3,  9,  7,  7, 10,  2],
         [ 7,  9,  9,  4,  3,  4],
         [ 7,  4,  7,  6,  8,  1],
        

In [29]:
test2

array([[0, 3, 8],
       [4, 1, 4],
       [5, 0, 3]], dtype=int32)

In [30]:
test3=np.random.randint(0,10,size=(3,3,3))
test3

array([[[1, 4, 4],
        [4, 0, 0],
        [8, 4, 6]],

       [[9, 3, 3],
        [2, 1, 2],
        [1, 3, 4]],

       [[1, 1, 0],
        [7, 8, 4],
        [3, 5, 6]]], dtype=int32)

In [31]:
test3[:2,:1]

array([[[1, 4, 4]],

       [[9, 3, 3]]], dtype=int32)

In [32]:
test2

array([[0, 3, 8],
       [4, 1, 4],
       [5, 0, 3]], dtype=int32)

In [33]:
test2**2

array([[ 0,  9, 64],
       [16,  1, 16],
       [25,  0,  9]], dtype=int32)

In [34]:
np.std(test2)

np.float64(2.4241582476968255)

In [35]:
np.sum(test3)

np.int64(94)

In [36]:
np.sum(test_array)

np.int64(1987)

In [37]:
np.mean(test_array)

np.float64(5.519444444444445)

In [38]:
test2

array([[0, 3, 8],
       [4, 1, 4],
       [5, 0, 3]], dtype=int32)

In [39]:
test2.reshape(9,1)

array([[0],
       [3],
       [8],
       [4],
       [1],
       [4],
       [5],
       [0],
       [3]], dtype=int32)

In [40]:
test2.reshape(9,1).transpose()

array([[0, 3, 8, 4, 1, 4, 5, 0, 3]], dtype=int32)

In [41]:
mat1=np.random.randint(0,100,size=(5,3))
mat2=np.random.randint(0,100,size=(3,1))

In [42]:
np.dot(mat1,mat2)

array([[10698],
       [10368],
       [16328],
       [14502],
       [ 9450]], dtype=int32)