In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

In [2]:
x,y=make_classification(n_samples=1000,n_informative=5,n_classes=5,n_features=10)

In [3]:
x

array([[ 1.28365434, -0.59775388,  0.58415286, ..., -1.28555861,
         1.7314011 ,  1.16660344],
       [ 0.03685029,  0.17127962, -1.14704856, ...,  1.64662998,
         0.85558316,  1.09185554],
       [ 1.33932934,  0.57089688,  1.27471559, ..., -1.90416025,
         2.04300655,  0.27684947],
       ...,
       [-1.17908497, -2.50444528, -3.2226354 , ...,  0.32056682,
         1.78225891,  0.24220164],
       [-0.71294036, -0.74969177,  1.1031254 , ...,  1.4016071 ,
        -1.43921615,  0.63982503],
       [-1.03649671,  0.74142374, -3.0863456 , ...,  1.25805898,
         3.71631257,  1.48429956]])

In [4]:
y

array([3, 2, 4, 2, 0, 3, 1, 4, 2, 0, 3, 1, 3, 0, 2, 0, 4, 4, 1, 3, 4, 0,
       1, 3, 2, 4, 4, 2, 4, 2, 2, 2, 1, 2, 4, 1, 4, 4, 0, 0, 0, 3, 2, 0,
       3, 2, 1, 3, 4, 0, 3, 0, 1, 0, 2, 0, 2, 4, 2, 1, 2, 0, 4, 3, 1, 2,
       0, 1, 0, 0, 4, 0, 3, 2, 1, 0, 4, 1, 2, 0, 0, 4, 2, 2, 4, 4, 1, 3,
       4, 4, 1, 1, 3, 4, 1, 4, 1, 0, 4, 4, 2, 2, 3, 3, 4, 1, 2, 0, 3, 0,
       0, 4, 2, 4, 3, 1, 0, 3, 1, 0, 4, 0, 0, 0, 3, 4, 3, 0, 2, 0, 0, 2,
       0, 2, 1, 3, 0, 1, 1, 2, 4, 3, 1, 3, 4, 4, 1, 3, 0, 4, 3, 3, 4, 2,
       0, 1, 3, 1, 3, 0, 2, 4, 0, 0, 2, 3, 0, 1, 3, 3, 0, 4, 4, 3, 2, 1,
       3, 2, 2, 2, 1, 2, 0, 4, 0, 2, 3, 1, 4, 2, 4, 3, 3, 0, 4, 4, 2, 4,
       4, 1, 4, 0, 0, 2, 4, 4, 0, 2, 1, 3, 1, 1, 0, 0, 2, 0, 4, 3, 1, 0,
       2, 3, 1, 2, 4, 2, 2, 2, 1, 2, 3, 4, 1, 4, 3, 1, 0, 2, 1, 2, 2, 3,
       1, 4, 3, 0, 1, 4, 4, 2, 1, 0, 2, 2, 3, 0, 3, 4, 3, 3, 4, 0, 3, 0,
       0, 3, 1, 2, 3, 0, 4, 2, 3, 3, 0, 3, 3, 0, 0, 1, 0, 2, 1, 3, 4, 3,
       3, 3, 0, 1, 1, 0, 2, 0, 4, 0, 2, 4, 2, 0, 3,

In [5]:
model=LogisticRegression(multi_class="ovr")

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [7]:
model.fit(x_train,y_train)

/media/pratyaksh/New Volume/github/pythonProject/.venv1/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [8]:
model.score(x_test,y_test)

0.485

In [9]:
model.predict(x_test)

array([4, 2, 4, 1, 1, 1, 0, 2, 0, 2, 1, 4, 0, 0, 4, 3, 0, 0, 1, 3, 2, 1,
       1, 1, 4, 1, 2, 0, 3, 2, 4, 1, 1, 2, 0, 4, 1, 2, 0, 1, 1, 1, 4, 4,
       2, 0, 4, 1, 4, 1, 3, 3, 2, 4, 0, 1, 0, 3, 1, 0, 0, 3, 1, 1, 1, 1,
       4, 3, 0, 3, 0, 3, 3, 2, 2, 3, 1, 1, 1, 0, 0, 2, 2, 1, 2, 3, 0, 2,
       3, 2, 3, 2, 4, 2, 1, 4, 0, 1, 4, 0, 0, 2, 3, 0, 0, 3, 1, 2, 3, 4,
       4, 1, 3, 3, 1, 1, 4, 0, 3, 1, 4, 4, 4, 3, 2, 4, 2, 0, 2, 0, 2, 2,
       4, 1, 3, 4, 4, 3, 0, 4, 2, 4, 1, 0, 4, 0, 4, 0, 2, 1, 4, 4, 2, 1,
       0, 2, 1, 4, 2, 2, 0, 2, 2, 4, 3, 2, 4, 0, 1, 4, 0, 3, 2, 0, 4, 0,
       1, 3, 2, 3, 1, 4, 0, 1, 2, 2, 4, 4, 0, 4, 0, 4, 4, 2, 2, 2, 4, 2,
       1, 2])

In [10]:
from sklearn.model_selection import RandomizedSearchCV

In [11]:
random=RandomizedSearchCV(model,param_distributions={"C":[0.1,1,10,100]},n_iter=10,cv=5)

In [12]:
random.fit(x_train,y_train)

/media/pratyaksh/New Volume/github/pythonProject/.venv1/lib/python3.12/site-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 4 is smaller than n_iter=10. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/media/pratyaksh/New Volume/github/pythonProject/.venv1/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/media/pratyaksh/New Volume/github/pythonProject/.venv1/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/media/pratyaksh/New Volume/github/pythonPr

RandomizedSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
                   param_distributions={'C': [0.1, 1, 10, 100]})

In [13]:
random.score(x_test,y_test)

0.485